### ISSUE TITLE
Session contains old data

### ISSUE THREAD

**Issue by vkalchenko** [subscribepro/subscribepro-magento2-ext#11]
Hi. 
We were able to catch an issue, when two orders were placed one by one, first contained subscription products, second one - did not. And then SP request failed for some reasons. Due to this fail, checkout session still contains data about previous order and Magento displays a message on "Order Success" page - You will receive a separate email confirmation for your product subscription(s).

What do you think about adding an additional session cleanup into the try-catch block of SubmitAllAfter observer?

**Comment by vkalchenko** [comment]
Please take a look on Pull Request

**Comment by john-sparwasser** [comment]
Hi vkalchenko, thank you for the pull request.

Do you have any steps to reproduce the error so I can test that these changes fix the issue?

**Comment by vkalchenko** [comment]
@john-sparwasser 
I think this error was a result of some specific conditions. Here's the video - https://drive.google.com/file/d/0BzLW5ku-kdfuT01iYmxsd2VaSkU/view?usp=sharing

Also, I found this exception 
`[2017-02-23 14:25:09] report.CRITICAL: Magento\Framework\Exception\NoSuchEntityException: Platform customer is not found. in /data/www/html/www.rxbar.com/htdocs/vendor/subscribepro/subscribepro-magento2-ext/Platform/Manager/Customer.php:69
Stack trace:
#0 /data/www/html/www.rxbar.com/htdocs/vendor/subscribepro/subscribepro-magento2-ext/Platform/Manager/Customer.php(45): Swarming\SubscribePro\Platform\Manager\Customer->getCustomer('testgorilla1+26...', false, NULL)
#1 /data/www/html/www.rxbar.com/htdocs/vendor/subscribepro/subscribepro-magento2-ext/Model/Quote/SubscriptionCreator.php(69): Swarming\SubscribePro\Platform\Manager\Customer->getCustomerById('38')
#2 /data/www/html/www.rxbar.com/htdocs/vendor/subscribepro/subscribepro-magento2-ext/Observer/Checkout/SubmitAllAfter.php(71): Swarming\SubscribePro\Model\Quote\SubscriptionCreator->createSubscriptions(Object(Gorilla\CorePatches\Model\Quote\Quote\Interceptor), Object(Magento\Sales\Model\Order))
#3 /data/www/html/www.rxbar.com/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Swarming\SubscribePro\Observer\Checkout\SubmitAllAfter->execute(Object(Magento\Framework\Event\Observer))
#4 /data/www/html/www.rxbar.com/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Swarming\SubscribePro\Observer\Checkout\SubmitAllAfter), Object(Magento\Framework\Event\Observer))
#5 /data/www/html/www.rxbar.com/htdocs/vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#6 /data/www/html/www.rxbar.com/htdocs/var/generation/Magento/Staging/Model/Event/Manager/Proxy.php(95): Magento\Staging\Model\Event\Manager->dispatch('checkout_submit...', Array)
#7 /data/www/html/www.rxbar.com/htdocs/vendor/magento/module-quote/Model/QuoteManagement.php(363): Magento\Staging\Model\Event\Manager\Proxy->dispatch('checkout_submit...', Array)
#8 [internal function]: Magento\Quote\Model\QuoteManagement->placeOrder(132, Object(Magento\Quote\Model\Quote\Payment))
#9 /data/www/html/www.rxbar.com/htdocs/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)
#10 /data/www/html/www.rxbar.com/htdocs/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#11 /data/www/html/www.rxbar.com/htdocs/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#12 /data/www/html/www.rxbar.com/htdocs/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#13 /data/www/html/www.rxbar.com/htdocs/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /data/www/html/www.rxbar.com/htdocs/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#15 /data/www/html/www.rxbar.com/htdocs/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))`

but I can't confirm that is't related directly to provided video.

**Comment by garthbrantley** [comment]
Added recommend session cleanup code.
