### ISSUE TITLE
Installation error on Magento 2.4.4 version

### ISSUE THREAD

**Issue by ninjacoder30** [subscribepro/subscribepro-magento2-ext#147]
getting the following error when trying to install the plugin on Magento 2.4.4 Enterprise version 

composer2 require subscribepro/subscribepro-magento2-ext
 
`Using version ^1.5 for subscribepro/subscribepro-magento2-ext
./composer.json has been updated
Running composer update subscribepro/subscribepro-magento2-ext
Loading composer repositories with package information
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - subscribepro/subscribepro-magento2-ext[1.5.10, ..., 1.5.15] require subscribepro/subscribepro-php ~1.0.24 -> satisfiable by subscribepro/subscribepro-php[1.0.24].
    - subscribepro/subscribepro-magento2-ext[1.5.4, ..., 1.5.9] require subscribepro/subscribepro-php ~1.0.23 -> satisfiable by subscribepro/subscribepro-php[1.0.23, 1.0.24].
    - subscribepro/subscribepro-magento2-ext[1.5.2, ..., 1.5.3] require subscribepro/subscribepro-php ~1.0.19 -> satisfiable by subscribepro/subscribepro-php[1.0.19, ..., 1.0.24].
    - subscribepro/subscribepro-magento2-ext[1.5.0, ..., 1.5.1] require subscribepro/subscribepro-php ~1.0.18 -> satisfiable by subscribepro/subscribepro-php[1.0.18, ..., 1.0.24].
    - subscribepro/subscribepro-php[1.0.18, ..., 1.0.24] require guzzlehttp/guzzle ~6.0.1|~6.1|~6.2 -> found guzzlehttp/guzzle[6.0.1, ..., 6.5.8] but it conflicts with your root composer.json require (^7.4).
    - Root composer.json requires subscribepro/subscribepro-magento2-ext ^1.5 -> satisfiable by subscribepro/subscribepro-magento2-ext[1.5.0, ..., 1.5.15].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require subscribepro/subscribepro-magento2-ext:*" to figure out if any version is installable, or "composer require subscribepro/subscribepro-magento2-ext:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`

**Comment by karthik147** [comment]
Any update on this am seeing this issue with 2.4.5 installation as well

**Comment by ninjacoder30** [comment]
No. it was suppose to be done by july end but the development is still inprogress and we are waiting the same.

**Comment by karthik147** [comment]
Any approximate timeline that this would be completed?

**Comment by ninjacoder30** [comment]
i was told it would be done by 28 July but now there is no ETA

**Comment by DmitryFurs** [comment]
In our project, we circumvented this problem by temporarily using the [dev-guzzle-test](https://github.com/subscribepro/subscribepro-php/tree/guzzle-test) branch as version _1.0.24_. 
Here is an example from our composer.lock
```json
"require": {
    "subscribepro/subscribepro-php": "dev-guzzle-test as 1.0.24"
}
```

**Comment by adriansanta** [comment]
@DmitryFurs while using the composer alias solves the issue, you might want to consider the security implications of doing so: https://github.com/subscribepro/subscribepro-php/issues/43#issuecomment-1228096921
