### ISSUE TITLE
Native My Subscriptions page on Magento 2.4.5 and 2.4.6

### ISSUE THREAD

**Issue by garthbrantley** [subscribepro/subscribepro-magento2-ext#154]
On 2.4.6 Page title displays and nothing else.

On 2.4.5 Frequency controls and buttons broken on:

![image](https://user-images.githubusercontent.com/8466130/192362801-2abad3cd-3d11-4659-9a39-501b24e194b6.png)

**Comment by chrismshea** [comment]
Here's an image of what it should look like.
![SP_MySubscriptions](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/579dff35-2e4a-4ed7-8ad5-a2afd5f70206)
