### ISSUE TITLE
Unable to complete checkout with virtual product using saved payment profile and no saved address.

### ISSUE THREAD

**Issue by chrismshea** [subscribepro/subscribepro-magento2-ext#157]
PR: #179 

Stores > Configuration > Sales > Checkout > Checkout Options > Display Billing Address On = Payment Method

1. Create a customer on Frontend
2. Add a Stored Payment Profile in My Account
3. Attempt checkout for virtual product.

Result: Place Order button disabled as there is no address

**Comment by czettnersandor** [comment]
This needs more information. The stored payment method this extension is providing is for existing subscriptions only, it can't be used for new orders.

Or, are you referring to a different payment method?

**Comment by czettnersandor** [comment]
My test: 
![image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/263174/8667c42f-9cde-4d33-b513-9b782f1e8361)
![image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/263174/79c9b411-f263-40ff-bb66-90536ac6e8f8)
(it allows me to enter a new address)

**Comment by czettnersandor** [comment]
Please ignore this, I found the error when I try to check out with a subscription product
