### ISSUE TITLE
Billing Address is not saved upon order placement

### ISSUE THREAD

**Issue by peterjeongjmp** [subscribepro/subscribepro-magento2-ext#160]
Currently, after a buyer places an offline payment order in Magento, the billing address is not being saved to the Customer in SubscribePro. Because the address is not saved, the Subscription's _Billing Address_ will not be set. When it is time for their Subscription to renew, the automatic recurring order in SubscribePro will fail due to this error:
`400 response received with message: The shipping address is missing. Set the address and try again. `

The billing address from Magento should be saved on the Customer in SubscribePro and set as the _Billing Address_ in the _Payment_ section of their Subscription.

**Comment by chrismshea** [comment]
@czettnersandor Can you please review this one when testing the offline payments module?

**Comment by czettnersandor** [comment]
@chrismshea good call. The extension extends \Swarming\SubscribePro\Model\Quote\QuoteItem\SubscriptionCreator which is where the billing address is saved along with the shipping address. This is going to be pull requests for all 3 repositories.

**Comment by czettnersandor** [comment]
These 3 should be used together, so let me know if you would like me to update versioning and composer files, etc:
https://github.com/subscribepro/subscribepro-php/pull/47
https://github.com/subscribepro/subscribepro-magento2-ext/pull/189
https://github.com/subscribepro/subscribepro-magento2-offline-payments/pull/3

**Comment by garthbrantley** [comment]
@chrismshea Can you provide steps to reproduce the current issue (if it still exists)?
