### ISSUE TITLE
Subscriptions not created from customer reorder.

### ISSUE THREAD

**Issue by chrismshea** [subscribepro/subscribepro-magento2-ext#164]
PRs: https://github.com/subscribepro/subscribepro-magento2-ext/pull/245

## Issue Summary

Customer attempts to reorder from their account from a subscription recurring order.  The order is successful, but no new subscriptions created.  The subscription id's on the new order are those from the subscriptions used to create the recurring order.

Video of issue upon request.

**Comment by garthbrantley** [comment]
@chrismshea Step-by-step instructions to reproduce and screenshots are needed.

**Comment by chrismshea** [comment]
@garthbrantley I think this is thoroughly documented in #191 with the result seen in step 10.

**Comment by eugene-shab** [comment]
@garthbrantley Issue was fixed in the ticket [#191](https://github.com/subscribepro/subscribepro-magento2-ext/issues/191)
