### ISSUE TITLE
Order Callback | Support both versions of Partial Order Mode in M2 Order Callback

### ISSUE THREAD

**Issue by JenFaber** [subscribepro/subscribepro-magento2-ext#167]
PRs: #237 

On callback orders: When partial order is disabled in Subscribe Pro, have the value sent to the Magento Extension as false. When partial order is allowed in subscribe pro, have the value sent to the Magento extension as true.

Without this, partial orders will go through on callback orders.

![image](https://user-images.githubusercontent.com/129110609/236869048-e7ded6d3-6427-4d1d-af98-e86fec876c5d.png)

Debug Log when Allow Partial order is enabled
[M2_Order_Callback_Partial_True.log](https://github.com/subscribepro/platform/files/11274321/M2_Order_Callback_Partial_True.log)

Debug Log when Allow Partial order is disabled
[M2_Order_Callback_Partial_False.log](https://github.com/subscribepro/platform/files/11274320/M2_Order_Callback_Partial_False.log)

Ref: [platform #928](https://github.com/subscribepro/platform/issues/928)

**Comment by garthbrantley** [comment]
@eugene-shab A good test case for a partial order would be when you order 2 subscription items together in the same order, 1 item is in stock on M2, the other item is out of stock on M2.

Thank you.

**Comment by eugene-shab** [comment]
@garthbrantley  Fixed partial order mode on the Magento side

**Comment by chrismshea** [comment]
@eugene-shab 
## Partial Order Mode = False
**Partial Order Mode** = `Require all subscriptions to be successfully ordered`

**Expectations**
1. On the frontend of Magento 2 using a new customer create an order and subscribe to two unique items
2. In the Magento 2 Admin set one of the products to be Out of Stock
3. In Subscribe Pro trigger a manual order from the customer account for both items
![manual_order](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/a095ae72-10b6-4331-a05a-8c079b2f9b18)
4. Monitor the recent orders tab for the order to be run
5. Both subscription orders should be marked as failed.

**Current Behavior**
Only the Out of Stock item subscription order is marked failed.

## Partial Order Mode = True
**Partial Order Mode** = `Allow partial orders`

**Expectations**
Steps 1-4 from above
5. Only the Out of Stock item subscription should be marked as failed
6. An order should be placed for the other item.
