### ISSUE TITLE
Make Phone Number Optional for Adding New Payment Method 

### ISSUE THREAD

**Issue by sophiabanda** [subscribepro/subscribepro-magento2-ext#169]
PRs: #216

## Requirements

- On the My Account > My Credit Cards > Add & Edit Credit Card pages
- We want to honor the M2 configuration settings regarding customer address requirements
- Behavior of the address fields on the My Credit Cards page should follow the behavior on My Account > Address Book > Add / Edit Customer Address pages

![image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/8466130/2ac7f198-9ba8-41a5-b4d9-ea288094aad2)

## Issue report

Unable to add a new credit card to account unless a phone number is provided. 

**Steps to reproduce:**

_Sign into Magento as a customer_
Go to "Stored Payment Methods": .../vault/cards/listaction/
Click "Add New Card"

![sp-telephone-code](https://github.com/subscribepro/subscribepro-magento2-ext/assets/51414936/da133370-d7e7-43f9-b0f6-507978670bf3)
<img width="949" alt="Screenshot 2023-07-24 at 6 56 25 AM" src="https://github.com/subscribepro/subscribepro-magento2-ext/assets/51414936/8dbafb3a-5510-4a2a-9d3b-9b0c4c49d7fd">

Fill out all the fields, leave "Telephone" blank, and click "Save Card"
Observe that "Telephone" says "This is a required field" and you are unable to save the credit card
I added screenshots of the error and of the SubscribePro modules where this is hard-coded.

**Comment by sophiabanda** [comment]
From what I was able to find, Magento 2 does not require a phone number for saving a new credit card, that would fall on the payment processor, or on Authorize.net

**Comment by eugene-shab** [comment]
@garthbrantley   I've updated the billing form based on Magento config
