### ISSUE TITLE
Order Callback | Interval value not stored in sales_order_item and not shown in order email.

### ISSUE THREAD

**Issue by chrismshea** [subscribepro/subscribepro-magento2-ext#182]
PRs: #236

When using order callback we are sending the interval label, but it is not being stored in the sales_order_item table instead the value is just null.  This causes it to not be included in the Magento order confirmation email.

`{"info_buyRequest":{"subscription_option":{"subscription_id":281591,"interval":null,"reorder_ordinal":"1","item_added_by_subscribe_pro":true,"item_fulfils_subscription":true,"next_order_date":"2023-07-16","create_new_subscription_at_checkout":false},"qty":1},"additional_options":[{"label":"Regular Delivery","value":""},{"label":"Subscription Id","value":281591}]}`

**Comment by eugene-shab** [comment]
@garthbrantley I added condition if quote item is fulfils subscription there is no cleaning interval value.
But I see an old comment/commit where David King mentioned `Fix bug that prevented the interval from updating in the cart, and clear the interval from the options if one-time is selected`. 2019-11-22 23:00:55
Do you know something about it?
