### ISSUE TITLE
Hosted My Subscriptions | Load hosted my subscriptions regardless if customer found in Subscribe Pro

### ISSUE THREAD

**Issue by chrismshea** [subscribepro/subscribepro-magento2-ext#184]
PRs: [#239](https://github.com/subscribepro/subscribepro-magento2-ext/pull/239)

We would like to implement this behavior on the My Subscriptions page - When Hosted My Subscriptions option configured:

- **Option 1** - Create a Subscribe Pro customer record, then get a customer scoped OAuth token and launch My Subscriptions widget

## Issue Report

Code:
https://github.com/subscribepro/subscribepro-magento2-ext/blob/618b405d50dde0d76aaa0db8101f6fb93927ae84/view/frontend/templates/customer/subscriptions.phtml#L4C19-L4C40

When a customer loads the My Subscriptions page in the My Account section and an account for the customer is not found under their email address the native My Subscriptions page is displayed.

The styling is different from native My Subscriptions page to Hosted My Subscriptions.  I feel the hosted widget should always be loaded when enabled.

I believe the reason it is not being attempted to load because an exception would be generated because we do not have a customer id to generate a oauth token with in SP.

Some changes could be made both in the hosted widgets, and in the module to display the widget with the standard message when customer does not have any active subscriptions.

**Native My Subs - No Subs**
![Native_MySubs_Displayed](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/7d64e724-b12f-45d1-a31f-c64f89b5eeb8)

**Hosted Widget - No Subs**
![Hosted_No_Subs](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/0c2870d7-1287-4a82-bb86-f4e543f3b45f)

**Comment by garthbrantley** [comment]
Here are a few options and details:
* One possibility to consider - Logged in customer arrives at My Subscriptions page
* Customer does not already have a Subscribe Pro customer record
* Option 1 - Create a Subscribe Pro customer record, then get a customer scoped OAuth token and launch My Subscriptions widget
* Option 2 - Get a "session" scoped OAuth token and launch My Subscriptions widget (Note we need to do work in the widget to better handle the "session" scoped token.

Refs:
* https://api.subscribepro.com/docs/rest#get|post--oauth-v2-token

**Comment by eugene-shab** [comment]
@garthbrantley I completed the first option - when a customer doesn't have a customer account, it will create an account in the platform.
But when for the second option (get access token) I'm using the `session` scope I'm getting an error in the console
![image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1384207/46fb0323-175d-4d40-acb8-9f6e349c3e52)
I think that the scope `widget` is the right decision. Can you confirm it?
