### ISSUE TITLE
My Credit Cards | Edit/Add Card | Exception

### ISSUE THREAD

**Issue by chrismshea** [subscribepro/subscribepro-magento2-ext#187]
PR: #190

When attempting to edit my saved credit card I get an exception.  See attached screenshot.

![M246_EditCard](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/4727a863-4bc4-486b-bbfd-654e1bfcae3d)

**Comment by czettnersandor** [comment]
I fixed this here:
https://github.com/subscribepro/subscribepro-magento2-ext/pull/190
The problem was the $block->helper call that was deprecated in 2.4
