### ISSUE TITLE
Cart price rule issue reported - `reorder_ordinal`

### ISSUE THREAD

**Issue by garthbrantley** [subscribepro/subscribepro-magento2-ext#191]
PRs: [#245](https://github.com/subscribepro/subscribepro-magento2-ext/pull/245)

Ensure that Reorder Ordinal is not set on cart line items when orders created using the
- Reorder feature by customer on front-end of M2 site in My Account
- Reorder feature used by admins in M2 admin panel

## Bug Report

There are two scenarios through which a reorder ordinal can (incorrectly) make its way into a quote / cart in Adobe Commerce. This allows for undesired application of cart price rules / discounts that are based on reorder ordinals in the conditions:

Reorder (from My Account > My Orders) of a recurring order
Failed recurring order (if it gets far enough to create a quote)
There is financial / revenue impact to both of these, while the first is obviously likely to be more prevalent.

To address this, a possible technical approach might be an observer for the sales_quote_save_before​ Adobe Commerce event, where the execute()​ function would loop through the items being added to the quote and strip out reorder_ordinal, subscription_id, and any other data which shouldn't persist into a new order.

**Comment by eugene-shab** [comment]
@garthbrantley If I understand correctly, the quote that is created during reordering should not contain `reorder_ordinary`. 

Can you provide if are there specific steps to reproduce a quote with an established value of `reorder_ordinary`?

I have tested different variations of reorder creation, `reorder_ordinary` value appears only when creating an order from the platform with the quote value `is_fulfilling` = true and `reorder_ordinary` = value, in other cases (My account and admin panel) quotes are created with `create_new_subscription_at_checkout` = true and without `reoder_ordinary`

**Comment by garthbrantley** [comment]
@chrismshea Can you attempt to reproduce this and then document steps-to-reproduce?

**Comment by chrismshea** [comment]
## Below Steps were done from Main at [4859774](https://github.com/subscribepro/subscribepro-magento2-ext/commit/4859774310fa420887e4d82ba476acd2fed82ea8)

### Steps to reproduce
1. On Magento 2 Frontend create a new subscription.
2. From Subscribe Pro create a Recurring type reorder
![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/ba7fe036-fa8d-43f5-9a93-58a92df5e9ec)
![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/40285418-59c0-4f67-8de4-dfbcbe44b220)
![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/287aebf1-d448-4e1a-9371-00d751b69358)
3. Verify the id of the order in Magento 2
![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/9bddc901-03c8-4626-aefe-c7c72dcf8c4e)
4. View the ordinal sent in the `sales_order_item` table.
![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/13789db0-e587-4e96-989a-d34ad06ac098)
5.  From the Customer My Account > My Orders find the successful recurring order placed
![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/a8ea0cd0-deb7-4053-9916-283a9179baa3)
6. Continue with a One Time Order
![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/adf4dbc4-4747-4843-be97-94b0ec02de59)
7. Note there is a subscription discount applied
![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/e7754558-9cd1-4765-bdfb-baa7cd72ce56)
8. View the placed order and note the `interval` and `subscription id` from the original recurring order from SP
![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/9d4223e8-de34-43e4-a0c3-e5f45bc8100a)
9. View the record in the DB `sales_order_item` table, and see the `reorder_ordinal` used from the original recurring order from SP
![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/c1ce9d12-c14c-47f9-a8e0-181d65923ccd)
10.  Same results occur if choosing regular deliver from reorder of original recurring order.
![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/0b9354f7-f2e7-482d-abe0-fa10dbceb856)

### These issues do not occur if doing a reorder from the sp recurring order in the admin one time or regular.

1. Create reorder from recurring order in admin
![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/be0c35c2-15c9-4851-bd6d-c9c93c05890b)
2. No subscription created, and no reused ordinal or sub id
![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/30aadfaa-f947-4cfc-a3f6-6256ba292dfc)
3. Create a regular delivery order from recurring order
![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/955aceac-cf39-4169-9e62-e6ac9af02fbb)
4. Subscription created, and new sub id and no reorder_ordinal
![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1232258/3f2771a7-6978-4c0f-9d15-e84697b14f58)

**Comment by eugene-shab** [comment]
@garthbrantley Since during the reorder the data for the new quote is taken from the old one, I saved the default values for the subscription options. Now when the reorderer is triggered, item options will be reset

![image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1384207/372639a3-3a9c-4bcc-889e-a927a960cdb5)
