### ISSUE TITLE
Issue with Save Card in My Account

### ISSUE THREAD

**Issue by anuslabs** [subscribepro/subscribepro-magento2-ext#194]
We are experiencing an issue with the 'Save Card' option when attempting to use 'Auto Fill.' After selecting the auto-fill details, the 'Save Card' button does not enable. 
Attached is a screen recording of the issue.
[savecard.webm](https://github.com/subscribepro/subscribepro-magento2-ext/assets/33516252/e36517f2-5a4d-4e21-af03-95620c0de453)

**Comment by chrismshea** [comment]
It has been reported that this also occurs in checkout. https://www.loom.com/share/744f176de5d742f78890f90bf20e8464?sid=c9222d03-92cb-406a-8cbb-102b627c9bc6

**Comment by JenFaber** [comment]
Video from client as well with the error occurring in checkout: https://zwdrive.com/7f4kna
Client is reporting they're having multiple customers abandon the checkout as a result.

**Comment by eugene-shab** [comment]
@chrismshea @garthbrantley This issue is no longer relevant since the behavior on the checkout and wallet pages has been rebuilt. Discussion of the need to block the save card/create checkout button occurs in this task https://github.com/subscribepro/subscribepro-magento2-ext/issues/219
