### ISSUE TITLE
Module version isn't bumped with releases

### ISSUE THREAD

**Issue by JamesonNetworks** [subscribepro/subscribepro-magento2-ext#21]
The version in https://github.com/subscribepro/subscribepro-magento2-ext/blob/master/etc/module.xml isn't being incremented with releases so the setup_module version table doesn't reflect the released version. This makes it difficult to tell what version of the module is installed. There is also no version listed in the composer.json, so I'm not sure how to tell what version of the module I have installed in M2.

**Comment by john-sparwasser** [comment]
Thank you for raising this issue. We are going to make it policy to raise the module version with every release now.

**Comment by JamesonNetworks** [comment]
Cool! I actually didn't know about the 'composer show' command which will give you this information also. M2 is a little strange with regards to version numbers because internally they use modules 100.x.x, etc and then those are linked to the 2.1.5 versions of the platform. I don't know if there is a best practice, but it is really annoying that there are so many places to put potentially unmatched versions. Thanks for your time!
