### ISSUE TITLE
Pass additional fields in one-time transaction requests

### ISSUE THREAD

**Issue by garthbrantley** [subscribepro/subscribepro-magento2-ext#221]
PRs: #232, subscribepro/subscribepro-php#51

When no customer is logged in, SP payment method is enabled and user checks out with new CC:

Must pass these additional fields in the transaction request:

- `creditcard_type`
- `creditcard_first_digits`
- `creditcard_last_digits`
- `billing_address`

API docs:

- https://api-stage.subscribepro.com/docs/rest#post--services-v1-vault-tokens-{token}-authorize.{_format}
- https://api-stage.subscribepro.com/docs/rest#post--services-v1-vault-tokens-{token}-purchase.{_format}

![image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/8466130/db92a91d-59ac-4322-b406-a5852cd2ab18)

**Comment by eugene-shab** [comment]
@garthbrantley i've create a fix for it - https://github.com/subscribepro/subscribepro-php/pull/51

**Comment by garthbrantley** [comment]
@eugene-shab This is tested working.

However, you did not update the dependency in the extension composer.json. Doing that now.
