### ISSUE TITLE
Wallet Page - New Card a/ $N Auth - Use `/authorize` and `/void`

### ISSUE THREAD

**Issue by garthbrantley** [subscribepro/subscribepro-magento2-ext#223]
PRs: #234

When enabled, for the authorization feature on the wallet page:

- We must use the `/authorize` and `/void` API calls instead of `/verify` API calls
  - https://api.subscribepro.com/docs/rest#post--services-v1-vault-paymentprofiles-{id}-authorize.{_format}
  - https://api.subscribepro.com/docs/rest#post--services-v1-vault-transactions-{id}-void.{_format}
    - Instead of
  - https://api.subscribepro.com/docs/rest#post--services-v1-vault-paymentprofiles-{id}-verify.{_format}
- We must pass the configured (in M2 admin) amount for the authorization

**Comment by eugene-shab** [comment]
@garthbrantley The command `Verify` replaced by `Authorization` and `Void`
