### ISSUE TITLE
Clean up PaymentFields implementation

### ISSUE THREAD

**Issue by garthbrantley** [subscribepro/subscribepro-magento2-ext#240]
PRs: [#243](https://github.com/subscribepro/subscribepro-magento2-ext/pull/243)

- [ ] Remove styles related to Spreedly 3DS and other aspects of payments that were removed - For example: https://github.com/subscribepro/subscribepro-magento2-ext/blob/main/view/frontend/web/css/source/_module.less#L384
- [ ] Remove all extra console.logs - For example: https://github.com/subscribepro/subscribepro-magento2-ext/blob/main/view/frontend/web/js/view/payment/method-renderer/cc-form.js#L92
- [ ] Remove extra event handlers which aren't used - For example: 3DS2 is never used in admin checkout, so no `'challenge*'` handlers needed
- [ ] All Spreedly, Spreedly iframe related code removed - For example: https://github.com/search?q=repo%3Asubscribepro%2Fsubscribepro-magento2-ext%20spreedly&type=code

**Comment by eugene-shab** [comment]
@garthbrantley Added clean-up for Payment Fields functionality on Checkout and Wallet pages.

Files that related to admin page was cleaned in different PR [#214](https://github.com/subscribepro/subscribepro-magento2-ext/pull/214)
