### ISSUE TITLE
Use payment token from transaction response instead of from wallet entry / pay profile

### ISSUE THREAD

**Issue by garthbrantley** [subscribepro/subscribepro-magento2-ext#250]
PRs: SP [#252 ](https://github.com/subscribepro/subscribepro-magento2-ext/pull/252)   SPPHP [#53 ](https://github.com/subscribepro/subscribepro-php/pull/53)

Here:

- https://github.com/subscribepro/subscribepro-magento2-ext/blob/main/Gateway/Response/VaultDetailsHandler.php#L100

We should pull the payment token from the transaction response. From the newly added `payment_token` field in that response.

![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/8466130/cf3dad84-ca93-4e78-b198-92726db9b789)

**Comment by eugene-shab** [comment]
@garthbrantley Added updates to SubscribePro-php library and added fix to VaultDetailsHandler
