### ISSUE TITLE
Google Recaptcha Erroring in Magento Checkout after 1.7.1 Update

### ISSUE THREAD

**Issue by JenFaber** [subscribepro/subscribepro-magento2-ext#277]
PR: #290

## Issue description

Google Recaptcha showing validation errors after updating the Subscribe Pro M2 extension to version 1.7.1. After removing the Subscribe Pro module the Google Recaptcha is working.

Ref Internal Support Ticket: #11879

**Comment by JaimeD-SubscribePro** [comment]
We have another report of this issue, with internal support ticket #12290.  Google ReCaptcha is not working properly when Subscribe Pro is installed.

Subscribe Pro version: 1.7.3
Magento Version: 2.4.7
Using v2 invisible ReCaptcha. This issue reproduces with all available versions though (v2, v2 invisible, v3 invisible)
Using magento/module-re-captcha-checkout v1.1.2

It appears to be preventing ReCaptcha from setting the header X-ReCaptcha in place-order-mixin.js.
![image](https://github.com/user-attachments/assets/729ce64a-2360-4300-a2d5-e0581f9781a3)


Screenshots: 

![image](https://github.com/user-attachments/assets/00ed84e0-a545-487f-a27b-55497e68df53)
![image](https://github.com/user-attachments/assets/17a39d70-c79a-42e0-a948-939394b38d12)
![image](https://github.com/user-attachments/assets/c64d7367-b169-46a6-ba94-f3e8e7b678fe)
