### ISSUE TITLE
Unable to Select or Add Shipping Method with Shipper HQ

### ISSUE THREAD

**Issue by JenFaber** [subscribepro/subscribepro-magento2-ext#278]
After updating the Magento extension to 1.7.1, a client using shipper HQ is no longer able to select or add a new shipping address without receiving an error.

![image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/129110609/8a7c266a-9762-4151-b171-1053e4b239c3)

<img width="1792" alt="Screenshot 2024-03-29 at 11 44 19 AM" src="https://github.com/subscribepro/subscribepro-magento2-ext/assets/129110609/11d59f3a-665e-44d7-a07c-650d37d2651b">

Reproduction Steps: 

1. On a Magento environment on extension 1.7.1 with Shipper HQ enabled, go to the storefront and add a subscription item to your card (Environment #4096 for example).
2. Go to checkout
3. Add a new address or try to use an existing address (this can be added in the address book) and an error will occur.

**Comment by chrismshea** [comment]
Patch shared:
[subscribepro-shipping-estimation.patch](https://github.com/subscribepro/subscribepro-magento2-ext/files/15011424/subscribepro-shipping-estimation.patch)

**Comment by JenFaber** [comment]
Ticket: https://subscribepro.zendesk.com/agent/tickets/11873

**Comment by garthbrantley** [comment]
We will only fix this if any active, expected-to-be-around-for-a-while clients are using M2 + SHQ.

**Comment by chrismshea** [comment]
Previously supplied patch was not working for me.  This patch allows ShipperHQ methods to display, and I am able to complete checkout.  I verified that the shipping group as configured is properly being applied when a subscription is in the cart.

[Swarming_SubscribePro_ShipperHQ.patch](https://github.com/user-attachments/files/17058391/Swarming_SubscribePro_ShipperHQ.patch)
