### ISSUE TITLE
VaultDetailsHandler class not compatible with Magento 2.1.3

### ISSUE THREAD

**Issue by comdiler** [subscribepro/subscribepro-magento2-ext#7]
Class Swarming\SubscribePro\Gateway\Response\VaultDetailsHandler uses \Magento\Vault\Api\Data\PaymentTokenInterfaceFactory in consctuctor, and unfortunately Magento physically added \Magento\Vault\Api\Data\PaymentTokenInterfaceFactory interface in version 2.1.3.
Thin interface doens't have a di preference so DI manager tries to create an instance of \Magento\Vault\Api\Data\PaymentTokenInterfaceFactory. This causes fatal error.

Possible solution is to change \Magento\Vault\Api\Data\PaymentTokenInterfaceFactory in consctuctor to \Magento\Vault\Model\PaymentTokenFactory

**Comment by john-sparwasser** [comment]
Thank you. I will try this.

Unfortunately I am very unfamiliar with Magento2, as I have inherited this extension from an agency. Any more information you can gather about a possible fix would be awesome.

I am currently developing a patch that will (hopefully) be compatible with both Magento 2.1.2 and 2.1.3

**Comment by john-sparwasser** [comment]
https://github.com/magento/magento2/issues/8083

This thread is also suggesting fixes, but I am not familiar enough with Magento to follow exactly what they are saying

**Comment by john-sparwasser** [comment]
Fixed in version 1.0.7
