### ISSUE TITLE
Success page throws exception when using another payment method

### ISSUE THREAD

**Issue by jajajaime** [subscribepro/subscribepro-magento2-ext#86]
When checking out with a payment method that is not SP, the success page's block throws an exception because it tries to count subscription data that is not present on the checkout session.

> Exception #0 (Exception): Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/vendor/subscribepro/subscribepro-magento2-ext/Block/Checkout/Onepage/Success/Subscriptions.php on line 41

The code in question is the following
```php
/**
 * @return int
 */
public function getCountSubscriptions()
{
    return count($this->checkoutSession->getData(SubscriptionCreator::CREATED_SUBSCRIPTION_IDS));
}
```

I think it should first check if the data is there, and either return false or the count (although converting the whole thing to a bool should do it.)

**Comment by shilpambb** [comment]
The issue occurs on subscribe pro checkouts also when used on a checkout without subscriptions. It happens in php 7.2 and above. We are running into the same issue.

**Comment by eugene-shab** [comment]
@garthbrantley Can't reproduce this issue, I think this is not a relevant issue. Also, I found fixes related to this issue https://github.com/subscribepro/subscribepro-magento2-ext/commit/e28289a1d7413af59f957625666ea2f5577e11f2
